services:
  - type: web
    name: wingo-plans
    env: python
    plan: free
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
      python -m playwright install chromium
    startCommand: |
      gunicorn -w 2 -k gthread -b 0.0.0.0:$PORT app:create_app()
    autoDeploy: true
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: HEADLESS
        value: "1"

